server:
  port: 8082 # 运行端口
  max-http-header-size: 65535 # url最大限制
  session:
    timeout: 3600 # session会话超时时间，单位为秒
  tomcat:
    uri-encoding: utf-8

logging:
  # 如果 logging.file 、logging.path 两者都配置了，只会在项目的根目录下创建一个 .log 的文件
  # 因为没有 logback-spring.xml 配置文件，系统只认识 logging.file，不认识 logging.path

  # 所以要配置 logback-spring.xml，spring boot 会默认加载 path
  # 为什么不配置 logback.xml, 因为 logback.xml 会先 application.properties 加载
  # 而 logback-spring.xml 会后于 application.properties 加载
  # 这样我们在 application.properties 文中设置日志文件名称和文件路径才能生效。

  fileDir: d:/logs/
  level:
    root: error